name: pingo_assignment_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.3.0
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  dio: ^5.5.0+1
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  injectable: ^2.4.4
  intl: ^0.19.0
  path: ^1.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  auto_route_generator: ^8.1.0
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
